thresholds:
  error_rate:
    max: 0.1
    warning: 0.05
  latency:
    p95:
      max: 5000
      warning: 4000
  throughput:
    conversations_per_minute:
      min: 10
      warning: 15
  coverage:
    min: 80
    warning: 90